### ISSUE TITLE
Corrigir background

### ISSUE THREAD

**Issue by brunacabeco** [germanodusha/mercurio#4]
Tentar aproximar mais de uma viagem espacial e menos vagalume. Se for complexo, preferimos usar o gif mesmo e deixar pesado.

**Comment by guigallo** [comment]
@brunacabeco consigo colocar esse efeito no lugar:

[https://codepen.io/chrisyboy53/full/oXZzQb](https://codepen.io/chrisyboy53/full/oXZzQb)
